version: "3.8"
services:
  mongodb_api:
    container_name: api-mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_api_container:/data/db
  redis_api:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  mongodb_api_container:
